// Should be loaded after macros_jon

FullScreenMario.prototype.settings.maps = {
    // "mapDefault": "1-1",
    "mapDefault": "3sat-small",
    "locationDefault": "0",
    "groupTypes": ["Character", "Solid", "Scenery", "Text"],
    "requireEntrance": true,
    "screenAttributes": [
        "gravity",
        "setting",
        "time",
        "underwater",
        "floor",
        "jumpmod",
        "maxyvel",
        "maxyvelinv",
        "notime",
        "nokeys",
        "canscroll"
    ],
    "screenVariables": {
        "bottomDeathDifference": function (EightBitter) {
            return EightBitter.unitsize * 12;
        },
        "bottomPlatformMax": function (EightBitter) {
            var area = EightBitter.MapsHandler.getArea(),
                diff = EightBitter.MapScreener.bottomDeathDifference;
                
            if (!area) {
                return -1;
            }
                
            return (area.floor + diff) * EightBitter.unitsize;
        },
        "gravity": function (EightBitter) {
            var area = EightBitter.MapsHandler.getArea();
            
            if (area && area.underwater) {
                return EightBitter.gravity / 2.8;
            }
            
            return EightBitter.gravity;
        }
    },
    "onSpawn": FullScreenMario.prototype.addPreThing,
    "macros": {
        "Example": FullScreenMario.prototype.macroExample,
        "Fill": FullScreenMario.prototype.macroFillPreThings,
        "Pattern": FullScreenMario.prototype.macroFillPrePattern,
        "Floor": FullScreenMario.prototype.macroFloor,
        "Pipe": FullScreenMario.prototype.macroPipe,
        "PipeCorner": FullScreenMario.prototype.macroPipeCorner,
        "Tree": FullScreenMario.prototype.macroTree,
        "Shroom": FullScreenMario.prototype.macroShroom,
        "Water": FullScreenMario.prototype.macroWater,
        "CastleSmall": FullScreenMario.prototype.macroCastleSmall,
        "CastleLarge": FullScreenMario.prototype.macroCastleLarge,
        "Ceiling": FullScreenMario.prototype.macroCeiling,
        "Bridge": FullScreenMario.prototype.macroBridge,
        "Scale": FullScreenMario.prototype.macroScale,
        "PlatformGenerator": FullScreenMario.prototype.macroPlatformGenerator,
        "WarpWorld": FullScreenMario.prototype.macroWarpWorld,
        "CheepsStart": FullScreenMario.prototype.macroCheepsStart,
        "CheepsStop": FullScreenMario.prototype.macroCheepsStop,
        "BulletBillsStart": FullScreenMario.prototype.macroBulletBillsStart,
        "BulletBillsStop": FullScreenMario.prototype.macroBulletBillsStop,
        "LakituStop": FullScreenMario.prototype.macroLakituStop,
        "StartInsideCastle": FullScreenMario.prototype.macroStartInsideCastle,
        "EndOutsideCastle": FullScreenMario.prototype.macroEndOutsideCastle,
        "EndInsideCastle": FullScreenMario.prototype.macroEndInsideCastle,
        "Section": FullScreenMario.prototype.macroSection,
        "SectionPass": FullScreenMario.prototype.macroSectionPass,
        "SectionFail": FullScreenMario.prototype.macroSectionFail,
        "SectionDecider": FullScreenMario.prototype.macroSectionDecider,
        //
        "Hop": FullScreenMario.prototype.macroHop,
        "Gadget": FullScreenMario.prototype.macroGadget
    },
    "entrances": {
        "Normal": FullScreenMario.prototype.mapEntranceNormal,
        "Plain": FullScreenMario.prototype.mapEntrancePlain,
        "Castle": FullScreenMario.prototype.mapEntranceCastle,
        "Walking": FullScreenMario.prototype.mapEntranceWalking,
        "Vine": FullScreenMario.prototype.mapEntranceVine,
        "PipeVertical": FullScreenMario.prototype.mapEntrancePipeVertical,
        "PipeHorizontal": FullScreenMario.prototype.mapEntrancePipeHorizontal,
    },
    "patterns": (function (patterns) {
        var pattern,
            i;
        for (i in patterns) {
            if (patterns.hasOwnProperty(i)) {
                pattern = patterns[i];
                if (!pattern.length) {
                    continue;
                }
                
                // Pattern's last array should previously be ["blank", width]
                pattern.width = pattern[pattern.length - 1][1];
                pattern.pop();
            }
        }
        return patterns;
    })({
        "BackRegular": [
            ["HillLarge", 0, 0],
            ["Cloud1", 68, 68],
            ["Bush3", 92, 0],
            ["HillSmall", 128, 0],
            ["Cloud1", 156, 76],
            ["Bush1", 188, 0],
            ["Cloud3", 220, 68],
            ["Cloud2", 292, 76],
            ["Bush2", 332, 0],
            ["Blank", 384]
        ],
        "BackCloud": [
            ["Cloud2", 28, 64],
            ["Cloud1", 76, 32],
            ["Cloud2", 148, 72],
            ["Cloud1", 228, 0],
            ["Cloud1", 284, 32],
            ["Cloud1", 308, 40],
            ["Cloud1", 372, 0],
            ["Blank", 384]
        ],
        "BackFence": [
            ["PlantSmall", 88, 0],
            ["PlantLarge", 104, 0],
            ["Fence", 112, 0, 32],
            ["Cloud1", 148, 68],
            ["PlantLarge", 168, 0],
            ["PlantSmall", 184, 0],
            ["PlantSmall", 192, 0],
            ["Cloud1", 220, 76],
            ["Cloud2", 244, 68],
            ["Fence", 304, 0, 16],
            ["PlantSmall", 320, 0],
            ["Fence", 328, 0],
            ["PlantLarge", 344, 0],
            ["Cloud1", 364, 76],
            ["Cloud2", 388, 68],
            ["Blank", 384]
        ],
        "BackFenceMin": [
            ["PlantLarge", 104, 0],
            ["Fence", 112, 0, 32],
            ["Cloud1", 148, 68],
            ["PlantLarge", 168, 0],
            ["PlantSmall", 184, 0],
            ["PlantSmall", 192, 0],
            ["Cloud1", 220, 76],
            ["Cloud2", 244, 68],
            ["Fence", 304, 0, 16],
            ["PlantSmall", 320, 0],
            ["Fence", 328, 0],
            ["Cloud1", 364, 76],
            ["Cloud2", 388, 68],
            ["Blank", 384]
        ],
        "BackFenceMin2": [
            ["Cloud2", 4, 68],
            ["PlantSmall", 88, 0],
            ["PlantLarge", 104, 0],
            ["Fence", 112, 0],
            ["Fence", 128, 0, 16],
            ["Cloud1", 148, 68],
            // ["PlantLarge", 168, 0],
            ["PlantSmall", 184, 0],
            ["PlantSmall", 192, 0],
            ["Cloud1", 220, 76],
            ["Cloud2", 244, 68],
            ["Fence", 304, 0, 16],
            ["PlantSmall", 320, 0],
            ["Fence", 328, 0],
            ["PlantLarge", 344, 0],
            ["Cloud1", 364, 76],
            ["Cloud2", 388, 68],
            ["Blank", 384]
        ],
        "BackFenceMin3": [
            ["Cloud2", 4, 68],
            ["PlantSmall", 88, 0],
            ["PlantLarge", 104, 0],
            ["Fence", 112, 0, 4],
            ["Cloud1", 148, 68],
            ["PlantSmall", 184, 0],
            ["PlantSmall", 192, 0],
            ["Cloud1", 220, 76],
            ["Cloud2", 244, 68],
            ["Cloud1", 364, 76],
            ["Cloud2", 388, 68],
            ["Blank", 384]
        ]
    }),
    "library": (function (maps) {
        var library = {},
            i;
        
        for (i = 0; i < maps.length; i += 1) {
            library[maps[i].name] = maps[i];
        }
        
        return library;
    })
    ([
        {
            "name" : "jon",
            "locations" : [
                { "entry": "Castle"}
            ],
            "areas": [
                {
                    "setting": "Castle",
                    "creation": [
                        { "macro": "StartInsideCastle" },
                        // { "thing": "Stone", "y": 88, "width": 256 },
                        { "macro": "Floor", "x": 40, "y": 24 },
                        { "macro": "Water", "x": 48, "width": 40 },
                        { "macro": "Floor", "x": 88, "width": 64 },
                        { "macro": "Pipe", "x": 152, "y": 16, "height": "Infinity", "piranha": true, "entrance": 1 },
                        { "thing": "Brick", "x":0, "y":0, "width":2, "height":2},
                        { "thing": "Brick", "x":10, "y":10, "width":20, "height":20},
                        { "thing": "Brick", "x":20, "y":20, "width":20, "height":20},
                        { "thing": "Brick", "x":30, "y":30, "width":20, "height":20},
                        { "thing": "Brick", "x":40, "y":40, "width":20, "height":20},
                        { "thing": "Brick", "x":50, "y":50, "width":20, "height":20},
                        { "thing": "Brick", "x":60, "y":60, "width":20, "height":20},
                        { "thing": "Brick", "x":70, "y":70, "width":20, "height":20},
                        { "thing": "Brick", "x":80, "y":80, "width":20, "height":20},
                        { "thing": "Brick", "x":90, "y":90, "width":20, "height":20},
                        { "thing": "Brick", "x":100, "y":100, "width":20, "height":20},
                        { "thing": "Brick", "x":110, "y":110, "width":20, "height":20},
                        { "thing": "Brick", "x":120, "y":120, "width":20, "height":20},
                        { "thing": "Brick", "x":130, "y":130, "width":20, "height":20},
                        { "thing": "Brick", "x":140, "y":140, "width":20, "height":20},


                        // { "thing": "Stone", "x":0, "y":1},
                        // { "thing": "Stone", "x":0, "y":2},
                        // { "thing": "Brick", "x":1, "y":0},
                        // { "thing": "Brick", "x":2, "y":0},
                        // { "thing": "Brick", "x":20, "y":0},
                        // { "thing": "Stone", "x":10, "y":10}

                        { "macro": "Hop", "x":50, "y":80}


                    ]
                }
            ]
        }, 
        {
            "name": "1-1",
            "locations": [
                  { "xloc" : 1000, "yloc": 400},
                  { "entry": "Plain" },
                  { "entry": "PipeVertical" },
                  { "area": 1 },
            ],
            "areas": [
                {
                    "setting": "Overworld",
                    "blockBoundaries": true,
                    "creation": [
                        { "macro": "Pattern", "pattern": "BackRegular", "repeat": 5 },
                        { "macro": "Floor", "width": 552 },
                        { "thing": "DecorativeBack", "x": 20, "y": 88 },
                        { "thing": "DecorativeDot", "x": 21.5, "y": 46.5 },
                        { "thing": "DecorativeDot", "x": 21.5, "y": 86.5 },
                        { "thing": "CustomText", "x": 20, "y": 36, "texts": [
                            { "text": "MOVE: ARROWS/WASD", "offset": 12 },
                            { "text": "FIRE/SPRINT: SHIFT/CTRL" },
                            { "text": "PAUSE: P/RIGHTCLICK", "offset": 8 } 
                        ]},
                        { "thing": "CustomText", "x": 24.5, "y": 84, "size": "Large", "texts": [
                            { "text": "SUPER" }
                        ]},
                        { "thing": "CustomText", "x": 24.5, "y": 68, "size": "Huge", "texts": [
                            { "text": "MARIO BROS." }
                        ]},
                        { "thing": "DecorativeDot", "x": 105.5, "y": 46.5 },
                        { "thing": "DecorativeDot", "x": 105.5, "y": 86.5 },
                        { "thing": "CustomText", "x": 52, "y": 44, "size": "Colored", "texts": [
                            { "text": "©1985 NINTENDO" }
                        ]},
                        { "thing": "Block", "x": 128, "y": 32 },
                        { "thing": "Brick", "x": 160, "y": 32 },
                        { "thing": "Block", "x": 168, "y": 32, "contents": "Mushroom" },
                        { "thing": "Goomba", "x": 176, "y": 8 },
                        { "thing": "Brick", "x": 176, "y": 32 },
                        { "thing": "Block", "x": 176, "y": 64 },
                        { "thing": "Block", "x": 184, "y": 32 },
                        { "thing": "Brick", "x": 192, "y": 32 },
                        { "macro": "Pipe", "x": 224, "height": 16 },
                        { "macro": "Pipe", "x": 304, "height": 24 },
                        { "thing": "Goomba", "x": 340, "y": 8 },
                        { "macro": "Pipe", "x": 368, "height": 32 },
                        { "thing": "Goomba", "x": 412, "y": 8 },
                        { "thing": "Goomba", "x": 422, "y": 8 },
                        { "macro": "Pipe", "x": 456, "height": 32, "transport": 2 },
                        { "thing": "Block", "x": 512, "y": 40, "contents": "Mushroom1Up", "hidden": true },
                        { "macro": "Floor", "x": 568, "width": 120 },
                        { "thing": "Brick", "x": 616, "y": 32 },
                        { "thing": "Block", "x": 624, "y": 32, "contents": "Mushroom" },
                        { "thing": "Brick", "x": 632, "y": 32 },
                        { "thing": "Brick", "x": 640, "y": 32 },
                        { "thing": "Goomba", "x": 640, "y": 72 },
                        { "thing": "Brick", "x": 648, "y": 64 },
                        { "thing": "Brick", "x": 656, "y": 64 },
                        { "thing": "Goomba", "x": 656, "y": 72 },
                        { "macro": "Fill", "thing": "Brick", "x": 664, "y": 64, "xnum": 5, "xwidth": 8 },
                        { "macro": "Floor", "x": 712, "width": 512 }, 
                        { "macro": "Fill", "thing": "Brick", "x": 728, "y": 64, "xnum": 3, "xwidth": 8 },
                        { "thing": "Brick", "x": 752, "y": 32, "contents": "Coin" },
                        { "thing": "Block", "x": 752, "y": 64 },
                        { "thing": "Goomba", "x": 776, "y": 8 },
                        { "thing": "Goomba", "x": 788, "y": 8 },
                        { "thing": "Brick", "x": 800, "y": 32 },
                        { "thing": "Brick", "x": 808, "y": 32, "contents": "Star" },
                        { "thing": "Block", "x": 848, "y": 32 },
                        { "thing": "Koopa", "x": 856, "y": 12 },
                        { "thing": "Block", "x": 872, "y": 32 },
                        { "thing": "Block", "x": 872, "y": 64, "contents": "Mushroom" },
                        { "thing": "Block", "x": 896, "y": 32 },
                        { "thing": "Goomba", "x": 912, "y": 8 },
                        { "thing": "Goomba", "x": 924, "y": 8 },
                        { "thing": "Brick", "x": 944, "y": 32 },
                        { "macro": "Fill", "thing": "Brick", "x": 968, "y": 64, "xnum": 3, "xwidth": 8 },
                        { "macro": "Fill", "thing": "Goomba", "x": 992, "y": 8, "xnum": 4, "xwidth": 16 },
                        { "thing": "Brick", "x": 1024, "y": 64 },
                        { "thing": "Brick", "x": 1032, "y": 32 },
                        { "thing": "Block", "x": 1032, "y": 64 },
                        { "thing": "Brick", "x": 1040, "y": 32 },
                        { "thing": "Block", "x": 1040, "y": 64 },
                        { "thing": "Brick", "x": 1048, "y": 64 },
                        { "thing": "Stone", "x": 1072, "y": 8 },
                        { "thing": "Stone", "x": 1080, "y": 16, "height": 16 },
                        { "thing": "Stone", "x": 1088, "y": 24, "height": 24 },
                        { "thing": "Stone", "x": 1096, "y": 32, "height": 32 },
                        { "thing": "Stone", "x": 1120, "y": 32, "height": 32 },
                        { "thing": "Stone", "x": 1128, "y": 24, "height": 24 },
                        { "thing": "Stone", "x": 1136, "y": 16, "height": 16 },
                        { "thing": "Stone", "x": 1144, "y": 8 },
                        { "thing": "Stone", "x": 1184, "y": 8 },
                        { "thing": "Stone", "x": 1192, "y": 16, "height": 16 },
                        { "thing": "Stone", "x": 1200, "y": 24, "height": 24 },
                        { "thing": "Stone", "x": 1208, "y": 32, "height": 32 },
                        { "thing": "Stone", "x": 1216, "y": 32, "height": 32 },
                        { "macro": "Floor", "x": 1240, "width": 656 },
                        { "thing": "Stone", "x": 1240, "y": 32, "height": 32 },
                        { "thing": "Stone", "x": 1248, "y": 24, "height": 24 },
                        { "thing": "Stone", "x": 1256, "y": 16, "height": 16 },
                        { "thing": "Stone", "x": 1264, "y": 8 },
                        { "macro": "Pipe", "x": 1304, "height": 16, "entrance": 1 },
                        { "thing": "Brick", "x": 1344, "y": 32 },
                        { "thing": "Brick", "x": 1352, "y": 32 },
                        { "thing": "Block", "x": 1360, "y": 32 },
                        { "thing": "Brick", "x": 1368, "y": 32 },
                        { "thing": "Goomba", "x": 1392, "y": 8 },
                        { "thing": "Goomba", "x": 1404, "y": 8 },
                        { "macro": "Pipe", "x": 1432, "height": 16 },
                        { "thing": "Stone", "x": 1448, "y": 8 },
                        { "thing": "Stone", "x": 1456, "y": 16, "height": 16 },
                        { "thing": "Stone", "x": 1464, "y": 24, "height": 24 },
                        { "thing": "Stone", "x": 1472, "y": 32, "height": 32 },
                        { "thing": "Stone", "x": 1480, "y": 40, "height": 40 },
                        { "thing": "Stone", "x": 1488, "y": 48, "height": 48 },
                        { "thing": "Stone", "x": 1496, "y": 56, "height": 56 },
                        { "thing": "Stone", "x": 1504, "y": 64, "height": 64, "width": 16 },
                        { "macro": "EndOutsideCastle", "x": 1584, "y": 0, "transport": { "map": "1-2" } }
                    ]
                }, {
                    "setting": "Underworld",
                    "blockBoundaries": true,
                    "creation": [
                        { "macro": "Ceiling", "x": 32, "width": 56 },
                        { "macro": "Floor", "x": 0, "y": 0, "width": 136 },
                        { "macro": "Fill", "thing": "Brick", "x": 0, "y": 8, "ynum": 11, "yheight": 8 },
                        { "macro": "Fill", "thing": "Brick", "x": 32, "y": 8, "xnum": 7, "ynum": 3, "xwidth": 8, "yheight": 8 },
                        { "macro": "Fill", "thing": "Coin", "x": 33, "y": 31, "xnum": 7, "ynum": 2, "xwidth": 8, "yheight": 16 },
                        { "macro": "Fill", "thing": "Coin", "x": 41, "y": 63, "xnum": 5, "ynum": 1, "xwidth": 8 },
                        { "thing": "PipeHorizontal", "x": 104, "y": 16, "transport": 1, "width": 16 },
                        { "thing": "PipeVertical", "x": 120, "y": 88, "height": 88 }
                    ]
                }
            ]
        },

{"name": "3sat-small",
"locations": [{"xloc": 60 + 1282 ,"yloc": 3840}],
"areas": [{"setting": "Castle","creation": [
{"macro": "Gadget","gadget": "START","reflect": false,"x": 0,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 162,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 162,"y": 162},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 0,"y": 162},

{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3840},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 1120,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 3840},
// {"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 4000,"y": 3840},
// {"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 4160,"y": 3840},

]}]},




{"name": "3sat","locations": [{"xloc": 1120,"yloc": 2720}],"areas": [{"setting": "Castle","creation": [{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3840},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 1120,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 3840},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 4000,"y": 3840},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 4160,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3840},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3680},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1120,"y": 3680},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 1280,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 3680},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 3680},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 4000,"y": 3680},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3680},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3520},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1120,"y": 3520},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1280,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 3520},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 1600,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 3520},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 3520},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 3840,"y": 3520},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 3520},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3520},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1120,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1280,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1600,"y": 3360},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 1760,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3360},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 3360},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 3680,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 3360},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3360},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1120,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1280,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1600,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1760,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 3200},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 2080,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3200},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 3200},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 3520,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 3200},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3200},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1120,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1280,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1600,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1760,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2080,"y": 3040},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 2240,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 3040},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 3040},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 3360,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 3040},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 3040},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1120,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1280,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1600,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1760,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 2080,"y": 2880},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 2240,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2880},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2880},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 2720},
{"macro": "Gadget","gadget": "START","reflect": false,"x": 1120,"y": 2720},
{"macro": "Gadget","gadget": "VARIABLE_L","reflect": true,"x": 1280,"y": 2720},
{"macro": "Gadget","gadget": "VARIABLE_L","reflect": false,"x": 1600,"y": 2720},
{"macro": "Gadget","gadget": "VARIABLE_L","reflect": true,"x": 1760,"y": 2720},
{"macro": "Gadget","gadget": "VARIABLE_L","reflect": false,"x": 2080,"y": 2720},
{"macro": "Gadget","gadget": "VARIABLE_L","reflect": true,"x": 2240,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2720},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2720},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1120,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1280,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1600,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 1760,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 2080,"y": 2560},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 2240,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2560},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2560},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2400},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 160,"y": 2400},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 320,"y": 2400},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 2400},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 2400},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 2400},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 2400},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 1120,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1280,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1600,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1760,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2080,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2240,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2400},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2400},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 2240},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 320,"y": 2240},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 2240},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 2240},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 2240},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 2240},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 2240},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 1280,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1600,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1760,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2080,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2240,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2240},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2240},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 2080},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 480,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 2080},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 2080},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 1600,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 1760,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2080,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2240,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 2080},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 2080},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1920},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 640,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 1920},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 1920},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 1760,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2080,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2240,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 1920},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 1920},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 640,"y": 1760},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 800,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 1760},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 1760},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 2080,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 2240,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 1760},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 1760},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 640,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 800,"y": 1600},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 960,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 1600},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 1600},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 2240,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 1600},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 1600},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 640,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 800,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 960,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1120,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1280,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1440,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1600,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1760,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1920,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2080,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2240,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2400,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2560,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2720,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 2880,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3040,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3200,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3360,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3520,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3680,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 1440},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4320,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 1440},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1280},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1280},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1280},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1280},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 640,"y": 1280},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 800,"y": 1280},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 960,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 1280},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 1280},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 3360,"y": 1280},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 3520,"y": 1280},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 3680,"y": 1280},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 3840,"y": 1280},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 4000,"y": 1280},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 4160,"y": 1280},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 4320,"y": 1280},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4480,"y": 1280},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 1120},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 1120},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 1120},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 1120},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 640,"y": 1120},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 800,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 1120},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 1120},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 3520,"y": 1120},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 3680,"y": 1120},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 3840,"y": 1120},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 4000,"y": 1120},
{"macro": "Gadget","gadget": "CROSSOVER_UR","reflect": false,"x": 4160,"y": 1120},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 1120},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 4480,"y": 1120},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 480,"y": 960},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 640,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 960},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 960},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 3680,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 3840,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 960},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 960},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 960},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 960},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 800},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 800},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 320,"y": 800},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 480,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 800},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 800},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 3840,"y": 800},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4000,"y": 800},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 800},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 800},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 800},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 640},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 160,"y": 640},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 320,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 640},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 640},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 4000,"y": 640},
{"macro": "Gadget","gadget": "PATH_UD","reflect": false,"x": 4160,"y": 640},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 640},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 640},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 480},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 160,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 320,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 480},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 4000,"y": 480},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 4160,"y": 480},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 480},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 480},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 160,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 320,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 480,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 640,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 800,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 960,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1120,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 1280,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 1440,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 1600,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 1760,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 1920,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 2080,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 2240,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 2400,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 2560,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 2720,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 2880,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_A","reflect": false,"x": 3040,"y": 320},
{"macro": "Gadget","gadget": "CLAUSE_B","reflect": false,"x": 3200,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3360,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3520,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3680,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3840,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4000,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4160,"y": 320},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 320},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 320},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 160},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": true,"x": 160,"y": 160},
{"macro": "Gadget","gadget": "ELBOW_DL","reflect": false,"x": 320,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 160},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 1440,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 1600,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 1760,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 1920,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 2080,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_D","reflect": false,"x": 2240,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 2400,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 2560,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 2720,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 2880,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_C","reflect": false,"x": 3040,"y": 160},
{"macro": "Gadget","gadget": "CLAUSE_D","reflect": false,"x": 3200,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3520,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3680,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 3840,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4000,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 4160,"y": 160},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4320,"y": 160},
{"macro": "Gadget","gadget": "PATH_DROP","reflect": false,"x": 4480,"y": 160},
{"macro": "Gadget","gadget": "EMPTY","reflect": false,"x": 0,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": true,"x": 160,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_UL","reflect": false,"x": 320,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 480,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 640,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 800,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 960,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1120,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1280,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1440,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1600,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1760,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 1920,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2080,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2240,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2400,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2560,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2720,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 2880,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3040,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3200,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3360,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3520,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3680,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 3840,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 4000,"y": 0},
{"macro": "Gadget","gadget": "PATH_RL","reflect": false,"x": 4160,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 4320,"y": 0},
{"macro": "Gadget","gadget": "ELBOW_T_INV","reflect": true,"x": 4480,"y": 0}]}]}



    ])
};